[package]
name = "shipwith-dev"
version = "0.1.0"
edition = "2021"
authors = ["Shankar"]
description = "Interactive architecture simulator for web apps"
repository = "https://github.com/srigirishankar/shipwith.dev"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
js-sys = "0.3.69"
console_error_panic_hook = { version = "0.1.7", optional = true }
console_log = "1.0"
log = "0.4"

web-sys = { version = "0.3.69", features = [
    "console",
    "Document",
    "Element",
    "HtmlElement",
    "HtmlCanvasElement",
    "Window",
    "MouseEvent",
    "WheelEvent",
    "TouchEvent",
    "TouchList",
    "Touch",
    "KeyboardEvent",
    "Performance",
]}

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ezing = "0.1"

[dev-dependencies]
wasm-bindgen-test = "0.3.42"

[profile.release]
lto = true
opt-level = 's'
